src/Entity/Game.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\GameRepository")
 */
class Game
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function __toString()
    {
        return $this->getName();
    }
}

src/Entity/GameUser.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;


/**
 * @ORM\Entity(repositoryClass="App\Repository\GameUserRepository")
 *
 * @UniqueEntity(fields={"User", "Game"})
 *
 */
class GameUser
{

    CONST MAX_HEALTH =  500;
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $health;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(nullable=false)
     */
    private $User;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Game")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Game;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getHealth(): ?int
    {
        return $this->health;
    }

    public function setHealth(int $health): self
    {
        $this->health = $health;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getGame(): ?Game
    {
        return $this->Game;
    }

    public function setGame(?Game $Game): self
    {
        $this->Game = $Game;

        return $this;
    }

    public function __toString()
    {
        return $this->getGame()->getName().' -- '.$this->getUser()->getUsername();
    }
}

src/Entity/Weapon.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

use App\Validator\Constraints as AssertApp;

/**
 * @ORM\Entity(repositoryClass="App\Repository\WeaponRepository")
 *
 * @AssertApp\ConstraintsUniqueWeaponLegendary
 */
class Weapon
{
    const MAX_AMMUNITION = 30;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     *
     * @Assert\Range(
     *      min = 0,
     *      max = 30,
     *      minMessage = "You must be at least {{ limit }} ammmunition",
     *      maxMessage = "You cannot have more than {{ limit }} ammunition"
     * )
     */
    private $ammunition;

    /**
     * @ORM\Column(type="boolean")
     */
    private $inHand;

    /**
     * @ORM\Column(type="integer")
     */
    private $scarcity;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\GameUser")
     */
    private $GameUser;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\WeaponType")
     * @ORM\JoinColumn(nullable=false)
     */
    private $WeaponType;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Game")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Game;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getAmmunition(): ?int
    {
        return $this->ammunition;
    }

    public function setAmmunition(int $ammunition): self
    {
        $this->ammunition = $ammunition;

        return $this;
    }

    public function getInHand(): ?bool
    {
        return $this->inHand;
    }

    public function setInHand(bool $inHand): self
    {
        $this->inHand = $inHand;

        return $this;
    }

    public function getScarcity(): ?int
    {
        return $this->scarcity;
    }

    public function setScarcity(int $scarcity): self
    {
        $this->scarcity = $scarcity;

        return $this;
    }


    public function getWeaponType(): ?WeaponType
    {
        return $this->WeaponType;
    }

    public function setWeaponType(?WeaponType $WeaponType): self
    {
        $this->WeaponType = $WeaponType;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getGameUser()
    {
        return $this->GameUser;
    }

    /**
     * @param mixed $GameUser
     */
    public function setGameUser(?GameUser $GameUser): self
    {
        $this->GameUser = $GameUser;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getGame()
    {
        return $this->Game;
    }

    /**
     * @param mixed $Game
     */
    public function setGame(Game $Game): self
    {
        $this->Game = $Game;

        return $this;
    }


    public function __toString()
    {
        return $this->getName();
    }
}

src/Form/GameType.php
<?php

namespace App\Form;

use App\Entity\Game;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class GameType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('createdAt')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Game::class,
        ]);
    }
}

src/Controller/GameController.php
<?php

namespace App\Controller;

use App\Entity\Game;
use App\Form\GameType;
use App\Repository\GameRepository;
use App\Repository\GameUserRepository;
use App\Repository\WeaponRepository;
use App\Service\GameUser\LoadGameUserInfo;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;


/**
 * @Route("/game")
 */
class GameController extends AbstractController
{
    /**
     * @Route("/", name="game_index", methods={"GET"})
     */
    public function index(GameRepository $gameRepository): Response
    {
        return $this->render('game/index.html.twig', [
            'games' => $gameRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="game_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $game = new Game();
        $form = $this->createForm(GameType::class, $game);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($game);
            $entityManager->flush();

            return $this->redirectToRoute('game_index');
        }

        return $this->render('game/new.html.twig', [
            'game' => $game,
            'form' => $form->createView(),
        ]);
    }

    /**
     *
     * @IsGranted("ROLE_USER")
     *
     * @Route("/{id}", name="game_show", methods={"GET"})
     */
    public function show(
        Game $game,
        GameUserRepository $gameUserRepository,
        WeaponRepository $weaponRepository,
        LoadGameUserInfo $loadGameUserInfo
    ): Response
    {
        $gameUser = $gameUserRepository->findOneBy(['User' => $this->getUser(), 'Game' => $game]);

        $gameUsers = $gameUserRepository->findBy(['Game' => $game]);

        $weapons = $weaponRepository->findBy(['Game' => $game]);

        $gameUsersInfo = [];

        foreach($gameUsers as $gameU){
            $gameUsersInfo[] = $loadGameUserInfo->load($gameU);
        }

        return $this->render(
            'game/show.html.twig',
            [
                'game' => $game,
                'gameUser' => $gameUser,
                'gameUsersInfo' => $gameUsersInfo,
                'weapons' => $weapons
            ]
        );
    }


    /**
     * @Route("/{id}/edit", name="game_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Game $game): Response
    {
        $form = $this->createForm(GameType::class, $game);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('game_index');
        }

        return $this->render('game/edit.html.twig', [
            'game' => $game,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="game_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Game $game): Response
    {
        if ($this->isCsrfTokenValid('delete'.$game->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($game);
            $entityManager->flush();
        }

        return $this->redirectToRoute('game_index');
    }
}

templates/game/_delete_form.html.twig
<form method="post" action="{{ path('game_delete', {'id': game.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ game.id) }}">
    <button class="btn">Delete</button>
</form>

templates/game/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/game/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Game{% endblock %}

{% block body %}
    <h1>Edit Game</h1>

    {{ include('game/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('game_index') }}">back to list</a>

    {{ include('game/_delete_form.html.twig') }}
{% endblock %}

templates/game/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Game index{% endblock %}

{% block body %}
    <h1>Game index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>CreatedAt</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for game in games %}
            <tr>
                <td>{{ game.id }}</td>
                <td>{{ game.name }}</td>
                <td>{{ game.createdAt ? game.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('game_show', {'id': game.id}) }}">show</a>
                    <a href="{{ path('game_edit', {'id': game.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('game_new') }}">Create new</a>
{% endblock %}

templates/game/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Game{% endblock %}

{% block body %}
    <h1>Create new Game</h1>

    {{ include('game/_form.html.twig') }}

    <a href="{{ path('game_index') }}">back to list</a>
{% endblock %}

templates/game/show.html.twig
{% extends 'base.html.twig' %}

{% import "macros.html.twig" as macros %}

{% block title %}Game{% endblock %}

{% block body %}


    {% if is_granted(constant('App\\Security\\Voter\\AppAccess::GAME_INGAME'), game) is same as(true) %}
        <h1 class="text-center">Welcome {{ gameUser.User.username }} to {{ game.name }}</h1>
        <div class="row">
            <div class="col-6">
                <h4 class="text-center">
                    Users
                </h4>
                <div class="row">
                    {% for gameUserInfo in gameUsersInfo  %}
                        {% if gameUser.id is not same as(gameUserInfo.gameUser.id) %}
                        <div class="col-6">
                            <h5 class="text-center">{{ gameUserInfo.gameUser.user.username }} - {{ gameUserInfo.gameUser.health }}</h5>
                        </div>
                        <div class="col-6">
                            {% if gameUserInfo.weapon is not null %}
                                <h5 class="text-center">{{ gameUserInfo.weapon.weapontype.name }} - {{ gameUserInfo.getReelDamage(gameUserInfo.weapon) }}</h5>
                            {% else %}
                                <h5 class="text-center">Pas d'arme chargé</h5>
                            {% endif %}
                        </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
            <div class="col-6">
                <h4 class="text-center">
                    Weapons
                </h4>
                <div class="row ">
                    {% for weapon in weapons %}
                        <div class="col-3">
                            <h5 class="text-left">
                                {{ weapon.weaponType.name }}
                            </h5>
                        </div>
                        <div class="col-9">
                            <h5 class="text-left">
                                {{ weapon.weaponType.damage }} - {{ macros.scarcity(weapon.scarcity) }}
                            </h5>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    {% else %}
        <div class="row">
            <div class="col-12">
                <h5 class="text-center"><a class="btn btn-success text-center" href="{{ path('game_user_new', {'id': game.id}) }}">m'inscrire à {{ game.name }}</a></h5>
            </div>
        </div>
    {% endif %}

    <div class="row">
        <div class="col-6">
            <a href="{{ path('game_index') }}">back to list</a>
        </div>
        <div class="col-6">
            <a href="{{ path('game_edit', {'id': game.id}) }}">edit</a>
        </div>
    </div>
    {{ include('game/_delete_form.html.twig') }}
{% endblock %}